# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_leaderboard_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('detail', models.TextField(max_length=500)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Round')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
