# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-27 09:06
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):

    Round = apps.get_model("game", "Round")
    Round.objects.create(
        number=0,
        title="Demo Round",
        detail="Solve each round question and add it up to find this answer",
        answer="4"
    )


def reverse_func(apps, schema_editor):

    Round = apps.get_model("game", "Round")
    Round.objects.filter(number=0).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0005_auto_20170627_2035'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
